services:
  database-game-critique:
    restart: unless-stopped
    ports: !reset []
    expose: 
      - "5432"
   
  redis:
    restart: unless-stopped
    ports: !reset []
    expose: 
      - "6379"
  
  game-critique-api:
    restart: unless-stopped
    container_name: game-critique-api
    pull_policy: build
    image: game-critique-api:v0.0.17
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
      
    environment:
      - PORT=${API_PORT:-3000}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@database-game-critique:5432/game-critique}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - IGDB_AUTH0_BASE_URL=${IGDB_AUTH0_BASE_URL?:Missing IGDB_AUTH0_BASE_URL}
      - IGDB_BASE_API_URL=${IGDB_BASE_API_URL?:Missing IGDB_BASE_API_URL}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID?:Missing IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET?:Missing IGDB_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE?:Missing AUTH0_AUDIENCE}
      - AUTH0_ISSUER_URL=${AUTH0_ISSUER_URL?:Missing AUTH0_ISSUER_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME?:Missing CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY?:Missing CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET?:Missing CLOUDINARY_API_SECRET}
      - HLTB_BASE_API_URL=${HLTB_BASE_API_URL?:Missing HLTB_BASE_API_URL}
      - SENTRY_DSN=${SENTRY_DSN?:Missing SENTRY_DSN}
      - HLTB_RANDOM_SEARCH_API_HASH=${HLTB_RANDOM_SEARCH_API_HASH?:Missing HLTB_RANDOM_SEARCH_API_HASH}
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    
    depends_on:
      database-game-critique:
        condition: service_healthy
      redis:
        condition: service_healthy

  game-critique-web:
    restart: unless-stopped
    container_name: game-critique-web
    pull_policy: build
    image: game-critique-web:v1.0.2
    build: 
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - PORT=${WEB_PORT:-3001}
      - API_URL=${API_URL:-http://game-critique-api:3000}
    ports:
      - "${WEB_PORT:-3001}:${WEB_PORT:-3001}"
    
    depends_on:
      - game-critique-api
