version: '3.8'

services:
  database-game-critique:
    image: postgres:16.1
    container_name: game-critique-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game-critique
      PGDATA: game-critique-db-data:/var/lib/postgresql/data
    volumes:
      - game-critique-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - redis-data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

volumes:
  game-critique-db-data:
  redis-data:
