version: '3.8'

services:
  database-game-critique:
    image: postgres:16.1
    container_name: game-critique-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game-critique
      PGDATA: ./data:/var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  pgdata: